=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.3/BdConcesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="BDConcesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo_de_coche" type="xs:string" />
                            <xs:element name="marca" type="xs:string" />
                            <xs:element name="modelo" type="xs:string" />
                            <xs:element name="matricula" type="xs:string" />
                            <xs:element name="potencia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="caballos" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="plazas" type="xs:string" />
                            <xs:element name="numero_de_puertas" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.3/cocesionarioxsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<BDConcesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="BDConcesionario.xsd">
    <coche>
        <codigo_de_coche>12345</codigo_de_coche>
        <marca>Toyota</marca>
        <modelo>Corolla</modelo>
        <matricula>ABC1234</matricula>
        <potencia>
            <caballos>120</caballos>
        </potencia>
        <plazas>5</plazas>
        <numero_de_puertas>4</numero_de_puertas>
    </coche>
    <coche>
        <codigo_de_coche>67890</codigo_de_coche>
        <marca>Ford</marca>
        <modelo>Focus</modelo>
        <matricula>XYZ5678</matricula>
        <potencia>
            <caballos>150</caballos>
        </potencia>
        <plazas>5</plazas>
        <numero_de_puertas>4</numero_de_puertas>
    </coche>
</BDConcesionario>
