=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.7/ventas.dtd
<!ELEMENT Informe (Cabecera, Datos)>
<!ELEMENT Cabecera (Descripcion, Fecha)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT Datos (Region+)>
<!ELEMENT Region (Trimestre+)>
<!ATTLIST Region nombre (Norte|Centro|Sur) #REQUIRED>
<!ELEMENT Trimestre (LibrosVendidos)>
<!ATTLIST Trimestre numero (1|2|3|4) #REQUIRED>
<!ELEMENT LibrosVendidos (#PCDATA)>

=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.7/ventas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Informe SYSTEM "ventas.dtd">
<Informe>
    <Cabecera>
        <Descripcion>Informe de ventas para las regiones Norte, Centro y Sur</Descripcion>
        <Fecha>30/12/2009</Fecha>
    </Cabecera>
    <Datos>
        <Region nombre="Norte">
            <Trimestre numero="1">
                <LibrosVendidos>24000</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="2">
                <LibrosVendidos>38600</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="3">
                <LibrosVendidos>NO_INFO</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="4">
                <LibrosVendidos>NO_INFO</LibrosVendidos>
            </Trimestre>
        </Region>
        <Region nombre="Centro">
            <Trimestre numero="1">
                <LibrosVendidos>NO_INFO</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="2">
                <LibrosVendidos>16080</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="3">
                <LibrosVendidos>25000</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="4">
                <LibrosVendidos>NO_INFO</LibrosVendidos>
            </Trimestre>
        </Region>
        <Region nombre="Sur">
            <Trimestre numero="1">
                <LibrosVendidos>27000</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="2">
                <LibrosVendidos>31400</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="3">
                <LibrosVendidos>40100</LibrosVendidos>
            </Trimestre>
            <Trimestre numero="4">
                <LibrosVendidos>30000</LibrosVendidos>
            </Trimestre>
        </Region>
    </Datos>
</Informe>
