=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.4/BDGestoria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="BDGestoria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Gestoria" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Empleado" type="xs:string"/>
              <xs:element name="Fecha" type="xs:string"/>
              <xs:element name="Cliente">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Descripción" type="xs:string"/>
                    <xs:element name="Número" type="xs:string"/>
                    <xs:element name="Vivienda">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="Coste" type="xs:string"/>
                          <xs:element name="Resumen" type="xs:string"/>
                          <xs:element name="Plazo" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="codigo" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="codigo" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.4/Gestoriaxsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<BDGestoria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="BDGestoria.xsd">

    <Gestoria codigo="">
        <Empleado></Empleado>
        <Fecha></Fecha>
        <Cliente codigo="">
            <Descripción></Descripción>
            <Número></Número>
            <Vivienda id="">
                <Coste></Coste>
                <Resumen></Resumen>
                <Plazo></Plazo>
            </Vivienda>
        </Cliente>
    </Gestoria>
</BDGestoria>
