=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.4/BDGestoria.dtd
<!ELEMENT BDGestoria (Gestoria*)>
<!ELEMENT Gestoria (Empleado, Fecha, Cliente)>
<!ATTLIST Gestoria codigo CDATA #REQUIRED>
<!ELEMENT Empleado (#PCDATA)>
<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT Cliente (Descripción, Número, Vivienda)>
<!ATTLIST Cliente codigo CDATA #REQUIRED>
<!ELEMENT Descripción (#PCDATA)>
<!ELEMENT Número (#PCDATA)>
<!ELEMENT Vivienda (Coste, Resumen, Plazo)>
<!ATTLIST Vivienda id CDATA #REQUIRED>
<!ELEMENT Coste (#PCDATA)>
<!ELEMENT Resumen (#PCDATA)>
<!ELEMENT Plazo (#PCDATA)>

=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.4/Gestoriadtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BDGestoria SYSTEM "BDGestoria.dtd">

<BDGestoria>
    <Gestoria codigo="">
        <Empleado></Empleado>
        <Fecha></Fecha>
        <Cliente codigo="">
            <Descripción></Descripción>
            <Número></Número>
            <Vivienda id="">
                <Coste></Coste>
                <Resumen></Resumen>
                <Plazo></Plazo>
            </Vivienda>
        </Cliente>
    </Gestoria>
</BDGestoria>
