=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.5/Alumnos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Alumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="NIF" type="xs:string"/>
                            <xs:element name="Resultado" type="xs:string"/>
                            <xs:element name="Observaciones" type="xs:string" minOccurs="0"/>
                            <xs:choice>
                                <xs:element name="IP" type="xs:string"/>
                                <xs:element name="MAC" type="xs:string"/>
                            </xs:choice>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== yoyi-88/LMSGI_UD4/ACTIVIDADES/4.5/Alumnosxsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Alumnos.xsd">

    <Alumno>
        <NIF>75845626L</NIF>
        <Resultado>apto</Resultado>
        <Observaciones>Progresa adecuadamente</Observaciones>
        <IP>325.514.18.107</IP>
    </Alumno>
    <Alumno>
        <NIF>87654321B</NIF>
        <Resultado>Problem√°tico</Resultado>
        <MAC>00:1j:2s:3b:4k:5n</MAC>
    </Alumno>
    <Alumno>
        <NIF>54869657M</NIF>
        <Resultado>No progresa adecuadamente</Resultado>
        <IP>854.475.7.88</IP>
    </Alumno>
</Alumnos>
